### PR TITLE
PHP CS fixer command executed

### PR DESCRIPTION
**Pull request by jonesdev**
The `native_function_invocation` option within PHP CS Fixer was used for this issue.

### CODE REVIEW

**Comment by ankitpokhrel** [comment]
@jonesdev Thank you for picking this up.

We are mocking native php functions on unit tests. Tests are failing because a call to `unlink($r)` can be mocked, but a call to `\unlink($r)` can't. I suggest you to exclude namespace from the following methods that are mocked during tests until we switch to proper integration tests:
```php
fseek, fread, fwrite, unlink, is_readable, hash_algos, base64_decode, connection_status
```

**Comment by jonesdev** [comment]
> @jonesdev Thank you for picking this up.
> 
> We are mocking native php functions on unit tests. Tests are failing because a call to `unlink($r)` can be mocked, but a call to `\unlink($r)` can't. I suggest you to exclude namespace from the following methods that are mocked during tests until we switch to proper integration tests:
> 
> ```
> fseek, fread, fwrite, unlink, is_readable, hash_algos, base64_decode, connection_status
> ```

Thanks for your advice - I'll try to rectify this later if I get a few minutes.

**Comment by jonesdev** [comment]
@ankitpokhrel 

I went about it via the following way: 

image

And the tests seem to be failing still - am I misunderstanding here?

`Failed asserting that exception of type "\TusPhp\Exception\FileException" is thrown.`

**Comment by ankitpokhrel** [comment]
@jonesdev you are in a right direction. Check the diff below, it works fine for me. You will need to do similar change in `Client.php` and `Server.php`.

```diff
--- a/src/File.php
+++ b/src/File.php
@@ -316,7 +316,7 @@ class File
             $this->seek($output, $this->offset);

             while ( ! \feof($input)) {
-                if (CONNECTION_NORMAL !== \connection_status()) {
+                if (CONNECTION_NORMAL !== connection_status()) {
                     throw new ConnectionException('Connection aborted by user.');
                 }

@@ -402,7 +402,7 @@ class File
      */
     public function seek($handle, int $offset, int $whence = SEEK_SET) : int
     {
-        $position = \fseek($handle, $offset, $whence);
+        $position = fseek($handle, $offset, $whence);

         if (-1 === $position) {
             throw new FileException('Cannot move pointer to desired position.');
@@ -423,7 +423,7 @@ class File
      */
     public function read($handle, int $chunkSize) : string
     {
-        $data = \fread($handle, $chunkSize);
+        $data = fread($handle, $chunkSize);

         if (false === $data) {
             throw new FileException('Cannot read file.');
@@ -445,7 +445,7 @@ class File
      */
     public function write($handle, string $data, $length = null) : int
     {
-        $bytesWritten = \is_int($length) ? \fwrite($handle, $data, $length) : \fwrite($handle, $data);
+        $bytesWritten = \is_int($length) ? fwrite($handle, $data, $length) : fwrite($handle, $data);

         if (false === $bytesWritten) {
             throw new FileException('Cannot write to a file.');
```

**Comment by jonesdev** [comment]
> @jonesdev you are in a right direction. Check the diff below, it works fine for me. You will need to do similar change in `Client.php` and `Server.php`.
> 
> ```diff
> --- a/src/File.php
> +++ b/src/File.php
> @@ -316,7 +316,7 @@ class File
>              $this->seek($output, $this->offset);
> 
>              while ( ! \feof($input)) {
> -                if (CONNECTION_NORMAL !== \connection_status()) {
> +                if (CONNECTION_NORMAL !== connection_status()) {
>                      throw new ConnectionException('Connection aborted by user.');
>                  }
> 
> @@ -402,7 +402,7 @@ class File
>       */
>      public function seek($handle, int $offset, int $whence = SEEK_SET) : int
>      {
> -        $position = \fseek($handle, $offset, $whence);
> +        $position = fseek($handle, $offset, $whence);
> 
>          if (-1 === $position) {
>              throw new FileException('Cannot move pointer to desired position.');
> @@ -423,7 +423,7 @@ class File
>       */
>      public function read($handle, int $chunkSize) : string
>      {
> -        $data = \fread($handle, $chunkSize);
> +        $data = fread($handle, $chunkSize);
> 
>          if (false === $data) {
>              throw new FileException('Cannot read file.');
> @@ -445,7 +445,7 @@ class File
>       */
>      public function write($handle, string $data, $length = null) : int
>      {
> -        $bytesWritten = \is_int($length) ? \fwrite($handle, $data, $length) : \fwrite($handle, $data);
> +        $bytesWritten = \is_int($length) ? fwrite($handle, $data, $length) : fwrite($handle, $data);
> 
>          if (false === $bytesWritten) {
>              throw new FileException('Cannot write to a file.');
> ```

Thank you, I'll try to work on this later.

**Comment by jonesdev** [comment]
@ankitpokhrel 

Output of PHPUnit:

`❯ vendor/bin/phpunit
PHPUnit 7.5.16 by Sebastian Bergmann and contributors.

........................SSSSSSSSSSS............................  63 / 219 ( 28%)
............................................................... 126 / 219 ( 57%)
............................................................... 189 / 219 ( 86%)
..............................                                  219 / 219 (100%)

Time: 1.57 seconds, Memory: 20.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 219, Assertions: 498, Skipped: 11.`

**Comment by ankitpokhrel** [comment]
Looks good now. Thanks!

**Pull request merged**
